////////////////////////////////////////////////////////////////////////
//
// XMLException.h
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.mcml.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

#ifndef XMLEXCEPTION_H_INCLUDED
#define XMLEXCEPTION_H_INCLUDED

namespace mcml {

class CXMLException
{
public:
	typedef enum
	{
		eError1,
		eError2,
		eDatabaseError,
	} ECode;

	CXMLException(int nCode, const tstring& sMessage) : m_nCode(nCode), m_sMessage(sMessage) {}

	int GetCode() { return m_nCode; }

	tstring GetInfo() {	return m_sMessage; }

protected:
	int		m_nCode;
	tstring	m_sMessage;
};


} // namespace mcml

#endif // XMLEXCEPTION_H_INCLUDED
