////////////////////////////////////////////////////////////////////////
//
// address_componentType.java
//
// This file was generated by XMLSpy 2014 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

package com.Geocode;

public class address_componentType extends com.altova.xml.TypeBase
{
	public static com.altova.xml.meta.ComplexType getStaticInfo() { return new com.altova.xml.meta.ComplexType(com.Geocode.GeocodeTypeInfo.binder.getTypes()[com.Geocode.GeocodeTypeInfo._altova_ti_altova_address_componentType]); }
	
	public address_componentType(org.w3c.dom.Node init)
	{
		super(init);
		instantiateMembers();
	}

	private void instantiateMembers()
	{

		long_name= new MemberElement_long_name (this, com.Geocode.GeocodeTypeInfo.binder.getMembers()[com.Geocode.GeocodeTypeInfo._altova_mi_altova_address_componentType._long_name]);
		short_name= new MemberElement_short_name (this, com.Geocode.GeocodeTypeInfo.binder.getMembers()[com.Geocode.GeocodeTypeInfo._altova_mi_altova_address_componentType._short_name]);
		type= new MemberElement_type (this, com.Geocode.GeocodeTypeInfo.binder.getMembers()[com.Geocode.GeocodeTypeInfo._altova_mi_altova_address_componentType._type]);
	}
	// Attributes


	// Elements
	
	public MemberElement_long_name long_name;

		public static class MemberElement_long_name
		{
			public static class MemberElement_long_name_Iterator implements java.util.Iterator
			{
				private org.w3c.dom.Node nextNode;
				private MemberElement_long_name member;
				public MemberElement_long_name_Iterator(MemberElement_long_name member) {this.member=member; nextNode=member.owner.getElementFirst(member.info);}
				public boolean hasNext() 
				{
					while (nextNode != null)
					{
						if (com.altova.xml.TypeBase.memberEqualsNode(member.info, nextNode))
							return true;
						nextNode = nextNode.getNextSibling();
					}
					return false;
				}
				
				public Object next()
				{
					long_nameType nx = new long_nameType(nextNode);
					nextNode = nextNode.getNextSibling();
					return nx;
				}
				
				public void remove () {}
			}
			protected com.altova.xml.TypeBase owner;
			protected com.altova.typeinfo.MemberInfo info;
			public MemberElement_long_name (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) { this.owner = owner; this.info = info;}
			public long_nameType at(int index) {return new long_nameType(owner.getElementAt(info, index));}
			public long_nameType first() {return new long_nameType(owner.getElementFirst(info));}
			public long_nameType last(){return new long_nameType(owner.getElementLast(info));}
			public long_nameType append(){return new long_nameType(owner.createElement(info));}
			public boolean exists() {return count() > 0;}
			public int count() {return owner.countElement(info);}
			public void remove() {owner.removeElement(info);}
			public void removeAt(int index) {owner.removeElementAt(info, index);}
			public java.util.Iterator iterator() {return new MemberElement_long_name_Iterator(this);}
			public com.altova.xml.meta.Element getInfo() { return new com.altova.xml.meta.Element(info); }
		}
	
	public MemberElement_short_name short_name;

		public static class MemberElement_short_name
		{
			public static class MemberElement_short_name_Iterator implements java.util.Iterator
			{
				private org.w3c.dom.Node nextNode;
				private MemberElement_short_name member;
				public MemberElement_short_name_Iterator(MemberElement_short_name member) {this.member=member; nextNode=member.owner.getElementFirst(member.info);}
				public boolean hasNext() 
				{
					while (nextNode != null)
					{
						if (com.altova.xml.TypeBase.memberEqualsNode(member.info, nextNode))
							return true;
						nextNode = nextNode.getNextSibling();
					}
					return false;
				}
				
				public Object next()
				{
					short_nameType nx = new short_nameType(nextNode);
					nextNode = nextNode.getNextSibling();
					return nx;
				}
				
				public void remove () {}
			}
			protected com.altova.xml.TypeBase owner;
			protected com.altova.typeinfo.MemberInfo info;
			public MemberElement_short_name (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) { this.owner = owner; this.info = info;}
			public short_nameType at(int index) {return new short_nameType(owner.getElementAt(info, index));}
			public short_nameType first() {return new short_nameType(owner.getElementFirst(info));}
			public short_nameType last(){return new short_nameType(owner.getElementLast(info));}
			public short_nameType append(){return new short_nameType(owner.createElement(info));}
			public boolean exists() {return count() > 0;}
			public int count() {return owner.countElement(info);}
			public void remove() {owner.removeElement(info);}
			public void removeAt(int index) {owner.removeElementAt(info, index);}
			public java.util.Iterator iterator() {return new MemberElement_short_name_Iterator(this);}
			public com.altova.xml.meta.Element getInfo() { return new com.altova.xml.meta.Element(info); }
		}
	
	public MemberElement_type type;

		public static class MemberElement_type
		{
			public static class MemberElement_type_Iterator implements java.util.Iterator
			{
				private org.w3c.dom.Node nextNode;
				private MemberElement_type member;
				public MemberElement_type_Iterator(MemberElement_type member) {this.member=member; nextNode=member.owner.getElementFirst(member.info);}
				public boolean hasNext() 
				{
					while (nextNode != null)
					{
						if (com.altova.xml.TypeBase.memberEqualsNode(member.info, nextNode))
							return true;
						nextNode = nextNode.getNextSibling();
					}
					return false;
				}
				
				public Object next()
				{
					typeType2 nx = new typeType2(nextNode);
					nextNode = nextNode.getNextSibling();
					return nx;
				}
				
				public void remove () {}
			}
			protected com.altova.xml.TypeBase owner;
			protected com.altova.typeinfo.MemberInfo info;
			public MemberElement_type (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) { this.owner = owner; this.info = info;}
			public typeType2 at(int index) {return new typeType2(owner.getElementAt(info, index));}
			public typeType2 first() {return new typeType2(owner.getElementFirst(info));}
			public typeType2 last(){return new typeType2(owner.getElementLast(info));}
			public typeType2 append(){return new typeType2(owner.createElement(info));}
			public boolean exists() {return count() > 0;}
			public int count() {return owner.countElement(info);}
			public void remove() {owner.removeElement(info);}
			public void removeAt(int index) {owner.removeElementAt(info, index);}
			public java.util.Iterator iterator() {return new MemberElement_type_Iterator(this);}
			public com.altova.xml.meta.Element getInfo() { return new com.altova.xml.meta.Element(info); }
		}
}
