/**
 * SchemaID.java
 *
 * This file was generated by XMLSPY 2004 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */

package jp.go.nict.mcml.xml.altova.types;

public class SchemaID extends SchemaNCName {
	public SchemaID() {
		super();
	}

	public SchemaID(String newvalue) {
		super(newvalue);
	}

	public SchemaID(SchemaID newvalue) {
		super((SchemaNCName)newvalue);
	}
}
