/**
 * SchemaInt.java
 *
 * This file was generated by XMLSPY 2004 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package jp.go.nict.mcml.xml.altova.types;

import java.math.BigInteger;
import java.math.BigDecimal;

public class SchemaInt implements SchemaTypeNumber {
  protected int value;
  protected boolean isempty;

  // construction
  public SchemaInt() {
    value = 0;
    isempty = true;
  }

  public SchemaInt(SchemaInt newvalue) {
    value = newvalue.value;
    isempty = newvalue.isempty;
  }

  public SchemaInt(int newvalue) {
    setValue( newvalue );
  }

  public SchemaInt(String newvalue) {
    parse( newvalue );
  }

  public SchemaInt(SchemaType newvalue) {
    assign( newvalue );
  }

  public SchemaInt(SchemaTypeNumber newvalue) {
    assign( (SchemaType)newvalue );
  }

  // getValue, setValue
  public int getValue() {
    return value;
  }

  public void setValue(int newvalue) {
    value = newvalue;
    isempty = false;
  }

  public void parse(String newvalue) {
    if( newvalue == null  ||  newvalue == "" ) {
      isempty = true;
      value = 0;
      return;
    }
    try {
      value = Integer.parseInt(newvalue);
      isempty = false;
    } catch( NumberFormatException e ) {
      throw new StringParseException(e);
    }
  }

  public void assign(SchemaType newvalue) {
    if( newvalue == null || newvalue.isEmpty() ) {
      isempty = true;
      value = 0;
      return;
    }
    if( newvalue instanceof SchemaTypeNumber ) {
      value = ( (SchemaTypeNumber) newvalue).intValue();
      isempty = false;
    }
    else
      throw new TypesIncompatibleException(newvalue, this);
  }

  // further
  public int hashCode() {
    return value;
  }

  public boolean equals(Object obj) {
    if (! (obj instanceof SchemaInt))
      return false;
    return value == ( (SchemaInt) obj).value;
  }

  public Object clone() {
    return new SchemaInt(value);
  }

  public String toString() {
    if( isempty )
      return "";
    return Integer.toString(value);
  }

  public int length() {
    return toString().length();
  }

  public boolean booleanValue() {
    return value != 0;
  }

  public boolean isEmpty() {
    return isempty;
  }

  public int compareTo(Object obj) {
    return compareTo( (SchemaInt) obj);
  }

  public int compareTo(SchemaInt obj) {
    return new Integer(value).compareTo(new Integer(obj.value));
  }

  // interface SchemaTypeNumber
  public int numericType() {
    return NUMERIC_VALUE_INT;
  }

  public int intValue() {
    return value;
  }

  public long longValue() {
    return value;
  }

  public BigInteger bigIntegerValue() {
    return BigInteger.valueOf(value);
  }

  public float floatValue() {
    return value;
  }

  public double doubleValue() {
    return value;
  }

  public BigDecimal bigDecimalValue() {
    return BigDecimal.valueOf(value);
  }
}
