/**
 * emptystring_datatype.java
 *
 * This file was generated by XMLSPY 2004 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package jp.go.nict.ssml.xml.types;

import jp.go.nict.ssml.xml.altova.types.*;

public class emptystring_datatype extends SchemaString {
	public emptystring_datatype() {
		super();
	}

	public emptystring_datatype(String newValue) {
		super(newValue);
		validate();
	}

	public void validate() {
		if (value != null && length() > getMaxLength())
			throw new jp.go.nict.ssml.xml.altova.xml.XmlException("Too long");
	}
	public int getMaxLength() {
		return 0;
	}
}
