/**
 * sentence.java
 *
 * This file was generated by XMLSPY 2004 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package jp.go.nict.ssml.xml.types;

import jp.go.nict.ssml.xml.altova.types.*;

public class sentence extends jp.go.nict.ssml.xml.altova.xml.Node {
	public sentence() {
		super();
	}

	public sentence(sentence node) {
		super(node);
	}

	public sentence(org.w3c.dom.Node node) {
		super(node);
	}

	public sentence(org.w3c.dom.Document doc) {
		super(doc);
	}
	public void adjustPrefix() {
		int count;
		count = getDomChildCount(Element, null, "voice");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Element, null, "voice", i);
			internalAdjustPrefix(tmpNode, true);
			new voice(tmpNode).adjustPrefix();
		}
		count = getDomChildCount(Element, null, "say-as");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Element, null, "say-as", i);
			internalAdjustPrefix(tmpNode, true);
			new say_as(tmpNode).adjustPrefix();
		}
		count = getDomChildCount(Element, null, "break");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Element, null, "break", i);
			internalAdjustPrefix(tmpNode, true);
			new break2(tmpNode).adjustPrefix();
		}
		count = getDomChildCount(Element, null, "token");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Element, null, "token", i);
			internalAdjustPrefix(tmpNode, true);
			new tokenType(tmpNode).adjustPrefix();
		}
		count = getDomChildCount(Element, null, "w");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Element, null, "w", i);
			internalAdjustPrefix(tmpNode, true);
			new tokenType(tmpNode).adjustPrefix();
		}
	}

	public int getvoiceMinCount() {
		return 1;
	}

	public int getvoiceMaxCount() {
		return 1;
	}

	public int getvoiceCount() {
		return getDomChildCount(Element, null, "voice");
	}

	public boolean hasvoice() {
		return hasDomChild(Element, null, "voice");
	}

	public voice getvoiceAt(int index) throws Exception {
		return new voice(getDomChildAt(Element, null, "voice", index));
	}

	public voice getvoice() throws Exception {
		return getvoiceAt(0);
	}

	public void removevoiceAt(int index) {
		removeDomChildAt(Element, null, "voice", index);
	}

	public void removevoice() {
		while (hasvoice())
			removevoiceAt(0);
	}

	public void addvoice(voice value) {
		appendDomElement(null, "voice", value);
	}

	public void insertvoiceAt(voice value, int index) {
		insertDomElementAt(null, "voice", index, value);
	}

	public void replacevoiceAt(voice value, int index) {
		replaceDomElementAt(null, "voice", index, value);
	}

	public int getsay_asMinCount() {
		return 1;
	}

	public int getsay_asMaxCount() {
		return 1;
	}

	public int getsay_asCount() {
		return getDomChildCount(Element, null, "say-as");
	}

	public boolean hassay_as() {
		return hasDomChild(Element, null, "say-as");
	}

	public say_as getsay_asAt(int index) throws Exception {
		return new say_as(getDomChildAt(Element, null, "say-as", index));
	}

	public say_as getsay_as() throws Exception {
		return getsay_asAt(0);
	}

	public void removesay_asAt(int index) {
		removeDomChildAt(Element, null, "say-as", index);
	}

	public void removesay_as() {
		while (hassay_as())
			removesay_asAt(0);
	}

	public void addsay_as(say_as value) {
		appendDomElement(null, "say-as", value);
	}

	public void insertsay_asAt(say_as value, int index) {
		insertDomElementAt(null, "say-as", index, value);
	}

	public void replacesay_asAt(say_as value, int index) {
		replaceDomElementAt(null, "say-as", index, value);
	}

	public int getbreak2MinCount() {
		return 1;
	}

	public int getbreak2MaxCount() {
		return 1;
	}

	public int getbreak2Count() {
		return getDomChildCount(Element, null, "break");
	}

	public boolean hasbreak2() {
		return hasDomChild(Element, null, "break");
	}

	public break2 getbreak2At(int index) throws Exception {
		return new break2(getDomChildAt(Element, null, "break", index));
	}

	public break2 getbreak2() throws Exception {
		return getbreak2At(0);
	}

	public void removebreak2At(int index) {
		removeDomChildAt(Element, null, "break", index);
	}

	public void removebreak2() {
		while (hasbreak2())
			removebreak2At(0);
	}

	public void addbreak2(break2 value) {
		appendDomElement(null, "break", value);
	}

	public void insertbreak2At(break2 value, int index) {
		insertDomElementAt(null, "break", index, value);
	}

	public void replacebreak2At(break2 value, int index) {
		replaceDomElementAt(null, "break", index, value);
	}

	public int gettokenMinCount() {
		return 1;
	}

	public int gettokenMaxCount() {
		return 1;
	}

	public int gettokenCount() {
		return getDomChildCount(Element, null, "token");
	}

	public boolean hastoken() {
		return hasDomChild(Element, null, "token");
	}

	public tokenType gettokenAt(int index) throws Exception {
		return new tokenType(getDomChildAt(Element, null, "token", index));
	}

	public tokenType gettoken() throws Exception {
		return gettokenAt(0);
	}

	public void removetokenAt(int index) {
		removeDomChildAt(Element, null, "token", index);
	}

	public void removetoken() {
		while (hastoken())
			removetokenAt(0);
	}

	public void addtoken(tokenType value) {
		appendDomElement(null, "token", value);
	}

	public void inserttokenAt(tokenType value, int index) {
		insertDomElementAt(null, "token", index, value);
	}

	public void replacetokenAt(tokenType value, int index) {
		replaceDomElementAt(null, "token", index, value);
	}

	public int getwMinCount() {
		return 1;
	}

	public int getwMaxCount() {
		return 1;
	}

	public int getwCount() {
		return getDomChildCount(Element, null, "w");
	}

	public boolean hasw() {
		return hasDomChild(Element, null, "w");
	}

	public tokenType getwAt(int index) throws Exception {
		return new tokenType(getDomChildAt(Element, null, "w", index));
	}

	public tokenType getw() throws Exception {
		return getwAt(0);
	}

	public void removewAt(int index) {
		removeDomChildAt(Element, null, "w", index);
	}

	public void removew() {
		while (hasw())
			removewAt(0);
	}

	public void addw(tokenType value) {
		appendDomElement(null, "w", value);
	}

	public void insertwAt(tokenType value, int index) {
		insertDomElementAt(null, "w", index, value);
	}

	public void replacewAt(tokenType value, int index) {
		replaceDomElementAt(null, "w", index, value);
	}
}
