/**
 * tokenType.java
 *
 * This file was generated by XMLSPY 2004 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package jp.go.nict.ssml.xml.types;

import jp.go.nict.ssml.xml.altova.types.*;

public class tokenType extends jp.go.nict.ssml.xml.altova.xml.Node {
	public tokenType() {
		super();
	}

	public tokenType(tokenType node) {
		super(node);
	}

	public tokenType(org.w3c.dom.Node node) {
		super(node);
	}

	public tokenType(org.w3c.dom.Document doc) {
		super(doc);
	}
	public void adjustPrefix() {
		int count;
	}
}
