/**
 * AudioType.java
 *
 * This file was generated by XMLSPY 2004 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package jp.go.nict.mcml.xml.types;

import jp.go.nict.mcml.xml.altova.types.*;

public class AudioType extends jp.go.nict.mcml.xml.altova.xml.Node {
	public AudioType() {
		super();
	}

	public AudioType(AudioType node) {
		super(node);
	}

	public AudioType(org.w3c.dom.Node node) {
		super(node);
	}

	public AudioType(org.w3c.dom.Document doc) {
		super(doc);
	}
	public void adjustPrefix() {
		int count;
		count = getDomChildCount(Attribute, null, "ChannelID");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Attribute, null, "ChannelID", i);
			internalAdjustPrefix(tmpNode, false);
		}
		count = getDomChildCount(Attribute, null, "BeginTimestamp");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Attribute, null, "BeginTimestamp", i);
			internalAdjustPrefix(tmpNode, false);
		}
		count = getDomChildCount(Attribute, null, "EndTimestamp");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Attribute, null, "EndTimestamp", i);
			internalAdjustPrefix(tmpNode, false);
		}
		count = getDomChildCount(Attribute, null, "EndPoint");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Attribute, null, "EndPoint", i);
			internalAdjustPrefix(tmpNode, false);
		}
		count = getDomChildCount(Element, null, "ModelType");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Element, null, "ModelType", i);
			internalAdjustPrefix(tmpNode, true);
			new ModelTypeType(tmpNode).adjustPrefix();
		}
		count = getDomChildCount(Element, null, "Signal");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Element, null, "Signal", i);
			internalAdjustPrefix(tmpNode, true);
			new SignalType(tmpNode).adjustPrefix();
		}
		count = getDomChildCount(Element, null, "Feature");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Element, null, "Feature", i);
			internalAdjustPrefix(tmpNode, true);
			new FeatureType(tmpNode).adjustPrefix();
		}
	}

	public int getChannelIDMinCount() {
		return 1;
	}

	public int getChannelIDMaxCount() {
		return 1;
	}

	public int getChannelIDCount() {
		return getDomChildCount(Attribute, null, "ChannelID");
	}

	public boolean hasChannelID() {
		return hasDomChild(Attribute, null, "ChannelID");
	}

	public SchemaInt getChannelIDAt(int index) throws Exception {
		return new SchemaInt(getDomNodeValue(getDomChildAt(Attribute, null, "ChannelID", index)));
	}

	public SchemaInt getChannelID() throws Exception {
		return getChannelIDAt(0);
	}

	public void removeChannelIDAt(int index) {
		removeDomChildAt(Attribute, null, "ChannelID", index);
	}

	public void removeChannelID() {
		while (hasChannelID())
			removeChannelIDAt(0);
	}

	public void addChannelID(SchemaInt value) {
		appendDomChild(Attribute, null, "ChannelID", value.toString());
	}

	public void addChannelID(String value) throws Exception {
		addChannelID(new SchemaInt(value));
	}

	public void insertChannelIDAt(SchemaInt value, int index) {
		insertDomChildAt(Attribute, null, "ChannelID", index, value.toString());
	}

	public void insertChannelIDAt(String value, int index) throws Exception {
		insertChannelIDAt(new SchemaInt(value), index);
	}

	public void replaceChannelIDAt(SchemaInt value, int index) {
		replaceDomChildAt(Attribute, null, "ChannelID", index, value.toString());
	}

	public void replaceChannelIDAt(String value, int index) throws Exception {
		replaceChannelIDAt(new SchemaInt(value), index);
	}

	public int getBeginTimestampMinCount() {
		return 1;
	}

	public int getBeginTimestampMaxCount() {
		return 1;
	}

	public int getBeginTimestampCount() {
		return getDomChildCount(Attribute, null, "BeginTimestamp");
	}

	public boolean hasBeginTimestamp() {
		return hasDomChild(Attribute, null, "BeginTimestamp");
	}

	public SchemaDateTime getBeginTimestampAt(int index) throws Exception {
		return new SchemaDateTime(getDomNodeValue(getDomChildAt(Attribute, null, "BeginTimestamp", index)));
	}

	public SchemaDateTime getBeginTimestamp() throws Exception {
		return getBeginTimestampAt(0);
	}

	public void removeBeginTimestampAt(int index) {
		removeDomChildAt(Attribute, null, "BeginTimestamp", index);
	}

	public void removeBeginTimestamp() {
		while (hasBeginTimestamp())
			removeBeginTimestampAt(0);
	}

	public void addBeginTimestamp(SchemaDateTime value) {
		appendDomChild(Attribute, null, "BeginTimestamp", value.toString());
	}

	public void addBeginTimestamp(String value) throws Exception {
		addBeginTimestamp(new SchemaDateTime(value));
	}

	public void insertBeginTimestampAt(SchemaDateTime value, int index) {
		insertDomChildAt(Attribute, null, "BeginTimestamp", index, value.toString());
	}

	public void insertBeginTimestampAt(String value, int index) throws Exception {
		insertBeginTimestampAt(new SchemaDateTime(value), index);
	}

	public void replaceBeginTimestampAt(SchemaDateTime value, int index) {
		replaceDomChildAt(Attribute, null, "BeginTimestamp", index, value.toString());
	}

	public void replaceBeginTimestampAt(String value, int index) throws Exception {
		replaceBeginTimestampAt(new SchemaDateTime(value), index);
	}

	public int getEndTimestampMinCount() {
		return 1;
	}

	public int getEndTimestampMaxCount() {
		return 1;
	}

	public int getEndTimestampCount() {
		return getDomChildCount(Attribute, null, "EndTimestamp");
	}

	public boolean hasEndTimestamp() {
		return hasDomChild(Attribute, null, "EndTimestamp");
	}

	public SchemaDateTime getEndTimestampAt(int index) throws Exception {
		return new SchemaDateTime(getDomNodeValue(getDomChildAt(Attribute, null, "EndTimestamp", index)));
	}

	public SchemaDateTime getEndTimestamp() throws Exception {
		return getEndTimestampAt(0);
	}

	public void removeEndTimestampAt(int index) {
		removeDomChildAt(Attribute, null, "EndTimestamp", index);
	}

	public void removeEndTimestamp() {
		while (hasEndTimestamp())
			removeEndTimestampAt(0);
	}

	public void addEndTimestamp(SchemaDateTime value) {
		appendDomChild(Attribute, null, "EndTimestamp", value.toString());
	}

	public void addEndTimestamp(String value) throws Exception {
		addEndTimestamp(new SchemaDateTime(value));
	}

	public void insertEndTimestampAt(SchemaDateTime value, int index) {
		insertDomChildAt(Attribute, null, "EndTimestamp", index, value.toString());
	}

	public void insertEndTimestampAt(String value, int index) throws Exception {
		insertEndTimestampAt(new SchemaDateTime(value), index);
	}

	public void replaceEndTimestampAt(SchemaDateTime value, int index) {
		replaceDomChildAt(Attribute, null, "EndTimestamp", index, value.toString());
	}

	public void replaceEndTimestampAt(String value, int index) throws Exception {
		replaceEndTimestampAt(new SchemaDateTime(value), index);
	}

	public int getEndPointMinCount() {
		return 0;
	}

	public int getEndPointMaxCount() {
		return 1;
	}

	public int getEndPointCount() {
		return getDomChildCount(Attribute, null, "EndPoint");
	}

	public boolean hasEndPoint() {
		return hasDomChild(Attribute, null, "EndPoint");
	}

	public SchemaDateTime getEndPointAt(int index) throws Exception {
		return new SchemaDateTime(getDomNodeValue(getDomChildAt(Attribute, null, "EndPoint", index)));
	}

	public SchemaDateTime getEndPoint() throws Exception {
		return getEndPointAt(0);
	}

	public void removeEndPointAt(int index) {
		removeDomChildAt(Attribute, null, "EndPoint", index);
	}

	public void removeEndPoint() {
		while (hasEndPoint())
			removeEndPointAt(0);
	}

	public void addEndPoint(SchemaDateTime value) {
		appendDomChild(Attribute, null, "EndPoint", value.toString());
	}

	public void addEndPoint(String value) throws Exception {
		addEndPoint(new SchemaDateTime(value));
	}

	public void insertEndPointAt(SchemaDateTime value, int index) {
		insertDomChildAt(Attribute, null, "EndPoint", index, value.toString());
	}

	public void insertEndPointAt(String value, int index) throws Exception {
		insertEndPointAt(new SchemaDateTime(value), index);
	}

	public void replaceEndPointAt(SchemaDateTime value, int index) {
		replaceDomChildAt(Attribute, null, "EndPoint", index, value.toString());
	}

	public void replaceEndPointAt(String value, int index) throws Exception {
		replaceEndPointAt(new SchemaDateTime(value), index);
	}

	public int getModelTypeMinCount() {
		return 0;
	}

	public int getModelTypeMaxCount() {
		return 1;
	}

	public int getModelTypeCount() {
		return getDomChildCount(Element, null, "ModelType");
	}

	public boolean hasModelType() {
		return hasDomChild(Element, null, "ModelType");
	}

	public ModelTypeType getModelTypeAt(int index) throws Exception {
		return new ModelTypeType(getDomChildAt(Element, null, "ModelType", index));
	}

	public ModelTypeType getModelType() throws Exception {
		return getModelTypeAt(0);
	}

	public void removeModelTypeAt(int index) {
		removeDomChildAt(Element, null, "ModelType", index);
	}

	public void removeModelType() {
		while (hasModelType())
			removeModelTypeAt(0);
	}

	public void addModelType(ModelTypeType value) {
		appendDomElement(null, "ModelType", value);
	}

	public void insertModelTypeAt(ModelTypeType value, int index) {
		insertDomElementAt(null, "ModelType", index, value);
	}

	public void replaceModelTypeAt(ModelTypeType value, int index) {
		replaceDomElementAt(null, "ModelType", index, value);
	}

	public int getSignalMinCount() {
		return 1;
	}

	public int getSignalMaxCount() {
		return Integer.MAX_VALUE;
	}

	public int getSignalCount() {
		return getDomChildCount(Element, null, "Signal");
	}

	public boolean hasSignal() {
		return hasDomChild(Element, null, "Signal");
	}

	public SignalType getSignalAt(int index) throws Exception {
		return new SignalType(getDomChildAt(Element, null, "Signal", index));
	}

	public SignalType getSignal() throws Exception {
		return getSignalAt(0);
	}

	public void removeSignalAt(int index) {
		removeDomChildAt(Element, null, "Signal", index);
	}

	public void removeSignal() {
		while (hasSignal())
			removeSignalAt(0);
	}

	public void addSignal(SignalType value) {
		appendDomElement(null, "Signal", value);
	}

	public void insertSignalAt(SignalType value, int index) {
		insertDomElementAt(null, "Signal", index, value);
	}

	public void replaceSignalAt(SignalType value, int index) {
		replaceDomElementAt(null, "Signal", index, value);
	}

	public int getFeatureMinCount() {
		return 0;
	}

	public int getFeatureMaxCount() {
		return Integer.MAX_VALUE;
	}

	public int getFeatureCount() {
		return getDomChildCount(Element, null, "Feature");
	}

	public boolean hasFeature() {
		return hasDomChild(Element, null, "Feature");
	}

	public FeatureType getFeatureAt(int index) throws Exception {
		return new FeatureType(getDomChildAt(Element, null, "Feature", index));
	}

	public FeatureType getFeature() throws Exception {
		return getFeatureAt(0);
	}

	public void removeFeatureAt(int index) {
		removeDomChildAt(Element, null, "Feature", index);
	}

	public void removeFeature() {
		while (hasFeature())
			removeFeatureAt(0);
	}

	public void addFeature(FeatureType value) {
		appendDomElement(null, "Feature", value);
	}

	public void insertFeatureAt(FeatureType value, int index) {
		insertDomElementAt(null, "Feature", index, value);
	}

	public void replaceFeatureAt(FeatureType value, int index) {
		replaceDomElementAt(null, "Feature", index, value);
	}
}
