/**
 * HTMLType.java
 *
 * This file was generated by XMLSPY 2004 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package jp.go.nict.mcml.xml.types;

import jp.go.nict.mcml.xml.altova.types.*;

public class HTMLType extends jp.go.nict.mcml.xml.altova.xml.Node {
	public HTMLType() {
		super();
	}

	public HTMLType(HTMLType node) {
		super(node);
	}

	public HTMLType(org.w3c.dom.Node node) {
		super(node);
	}

	public HTMLType(org.w3c.dom.Document doc) {
		super(doc);
	}
	public void adjustPrefix() {
		int count;
	}
}
