/**
 * ToType.java
 *
 * This file was generated by XMLSPY 2004 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSPY Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package jp.go.nict.mcml.xml.types;

import jp.go.nict.mcml.xml.altova.types.*;

public class ToType extends jp.go.nict.mcml.xml.altova.xml.Node {
	public ToType() {
		super();
	}

	public ToType(ToType node) {
		super(node);
	}

	public ToType(org.w3c.dom.Node node) {
		super(node);
	}

	public ToType(org.w3c.dom.Document doc) {
		super(doc);
	}
	public void adjustPrefix() {
		int count;
		count = getDomChildCount(Attribute, null, "URI");
		for (int i = 0; i < count; i++) {
			org.w3c.dom.Node tmpNode = getDomChildAt(Attribute, null, "URI", i);
			internalAdjustPrefix(tmpNode, false);
		}
	}

	public int getURIMinCount() {
		return 1;
	}

	public int getURIMaxCount() {
		return 1;
	}

	public int getURICount() {
		return getDomChildCount(Attribute, null, "URI");
	}

	public boolean hasURI() {
		return hasDomChild(Attribute, null, "URI");
	}

	public SchemaString getURIAt(int index) throws Exception {
		return new SchemaString(getDomNodeValue(getDomChildAt(Attribute, null, "URI", index)));
	}

	public SchemaString getURI() throws Exception {
		return getURIAt(0);
	}

	public void removeURIAt(int index) {
		removeDomChildAt(Attribute, null, "URI", index);
	}

	public void removeURI() {
		while (hasURI())
			removeURIAt(0);
	}

	public void addURI(SchemaString value) {
		appendDomChild(Attribute, null, "URI", value.toString());
	}

	public void addURI(String value) throws Exception {
		addURI(new SchemaString(value));
	}

	public void insertURIAt(SchemaString value, int index) {
		insertDomChildAt(Attribute, null, "URI", index, value.toString());
	}

	public void insertURIAt(String value, int index) throws Exception {
		insertURIAt(new SchemaString(value), index);
	}

	public void replaceURIAt(SchemaString value, int index) {
		replaceDomChildAt(Attribute, null, "URI", index, value.toString());
	}

	public void replaceURIAt(String value, int index) throws Exception {
		replaceURIAt(new SchemaString(value), index);
	}
}
